database:
  databaseGuildId: "876039624814899220"
  databaseChannelId: "928904657076649984"
  databaseMessageId: "932195496376819752"
  databaseName: BannedWords
wordMatching:
  caseSensitive: false
  fullWord: false
  ignoreBots: false
  deleteMatchedMessage: true
  defaultPunishment: timeout
  similarityMatch:
    enabled: true
    percentage: 0.7
punishments:
  timeout:
    duration: 10s
    defaultReason: You have been timed out for using a banned word.
  kick:
    defaultReason: You have been kicked for using a banned word.
  ban:
    defaultReason: You have been banned for using a banned word.
