interval: 2100
nicknames:
  - user: Ghex#7338
    guildId: "830456204735807529"
    randomize: false
    nicknames:
      - █░░░░░░█
      - ██░░░░░░
      - ███░░░░░
      - ████░░░░
      - █████░░░
      - ░█████░░
      - ░░████░░
      - ░░█████░
      - ░░░█████
      - ░░░░████
      - ░░░░░███
      - ░░░░░░██
      - █░░░░░░█
