enabled: true
botId: "841956155190411284"
consoleChannelId: "884753588105117726"
chatsChannelIf: "883269578791206942"
bannedWords:
  - fuck
  - dick
  - pussy
  - nigga
  - nigger
  - niger
  - niga
  - whore
  - slut
levels:
  "1":
    chatMessage: "%name%, Watch your words. It may be inappropriate for someone."
    consoleMessage: warn %name% Excessive profanity.
  "3":
    chatMessage: "%name%, Shall avoid from using lewd words exceedingly."
    consoleMessage: tempban %name% 30s Desist from using too much obscene words.
  "8":
    chatMessage: "%name%, You are being banned for excessive profanity."
    consoleMessage: ban %name% You are being banned for excessive profanity.
blacklistNames: []
matchWordOnly: false
