messageCommands:
  version:
    enabled: true
  stop:
    enabled: false
  help:
    enabled: true
interactionCommands:
  version:
    enabled: true
  stop:
    enabled: false
  help:
    enabled: true
setPresence: true
