messageCommands:
  version:
    enabled: true
  stop:
    enabled: true
  help:
    enabled: true
interactionCommands:
  version:
    enabled: true
  stop:
    enabled: true
  help:
    enabled: true
setPresence: true
