botNameKeywords:
  - McDown
  - McDown_pw
serverBotId: "841956155190411284"
consoleChannelId: "884753588105117726"
ingameChannelId: "883269578791206942"
messages:
  underAttack: |-
    Bot username keyword detected <:boi:898519549895389205>
    **Server Under Bot Attack enabled!**
    ```yml
    Turning on whitelist
    ```
  underAttackConsoleCommands:
    - whitelist on
    - whitelist reload
  attackCooldownMessage: |-
    Resetting bot name detection.
    **Server bot name detection reset!**
    ```yml
    Turning off whitelist
    ```
  attackCooldownCommands:
    - whitelist off
    - whitelist reload
