chatbot:
  enabled: true
  gender: male
  command:
    enabled: true
    name: ask
    description: Ask something!
channels:
  enableChannelWhitelist: true
  channelWhitelist:
    - '904211298177388595'
