token: ODU0MjMwMzY2MDg4MjAwMjMz.YMg6Bg.xvfAbyBdzPpnxVFFeTepruSuqfw # Bot token
#token: OTAzOTM5MzE5NDkwODI2MjYw.YX0RGA.Q9IyQarYuc6TMAjEH6bYd2-o0Ug # Bot token

embedColor: '#19AFFF'  # Colors for embed messages
commandPrefix: '!'  # Prefix for commands
owner: 'Ghex'  # Who owns this bot

guildId: # Only register slash commands for the given guild.

# Command permissions
permissions:
  # Message commands permissions
  messageCommands:
    # Enable message command permissions
    enable: true

    # Restrict commands for admin only (This is the command name)
    adminOnlyCommands: ['stop']

    # Command for moderator with kick and ban perms (This is the command name)
    moderatorOnlyCommands: ['antibot', 'antivpn', 'kick', 'ban', 'mute']
  
  # Slash commands permissions
  interactionCommands:
    # Enable slash commands permissions
    enable: true

    # Register slash commands
    registerSlashCommands: true

    # Restrict commands for admin only (This is the command name)
    adminOnlyCommands: ['stop', 'send']

    # Command for moderator with kick and ban perms (This is the command name)
    moderatorOnlyCommands: ['kick', 'ban', 'mute']

# Ignored channels based on IDs
blacklistChannels:            
  enabled: false  # Enable blacklisted channels

  # List of blacklisted channels
  channels: ['883269578791206942']
  convertToWhitelist: false  # Convert channels to whitelisted channels

# Custom bot presence
presence:
  enabled: true  # Enable presence
  status: ['dnd']  # Status of bot (online, idle, dnd, offline)  [this can be a string or an object for random value]
  type: ['listening']  # Type of status (playing, listening, watching, streaming) or enter a custom status  [this can be a string or an object for random value]
  activityName: ['!help', '7.6B people', '/help', '/cat', '/dog', 'Alputangina']  # Name your activity [this can be a string or an object for random value]


# Danger Zone!
# Edit this values below if you know what you're doing

# process errors logging. (Few options can stop some crashes)
processErrors:
  clientShardError: true
  processWarning: true
  processUnhandledRejection: true
  processUncaughtException: true

inviteFormat: https://discord.com/oauth2/authorize?client_id=%id%&permissions=8&scope=bot%20applications.commands   # Invite format for bot
language: 'config/language.yml'   # Langage file 
modulesFolder: 'modules'  # Define where's your modules (Changing this might cause problems to other modules)

version: 1.4.2    # Version (don't modify this value)