token: ODU0MjMwMzY2MDg4MjAwMjMz.YMg6Bg.xvfAbyBdzPpnxVFFeTepruSuqfw # Bot token
# token: OTAzOTM5MzE5NDkwODI2MjYw.YX0RGA.Q9IyQarYuc6TMAjEH6bYd2-o0Ug # Bot token

embedColor: '#19AFFF'  # Colors for embed messages
commandPrefix: '!'  # Prefix for commands
owner: 'Ghex'  # Who owns this bot

guildId: '876039624814899220' # Only register slash commands for the given guild.

# Command permissions
permissions:
  # Message commands permissions
  messageCommands:
    # Enable message command permissions
    enable: true

    # Restrict commands for admin only (This is the command name)
    adminOnlyCommands: ['stop']

    # Command for moderator with kick and ban perms (This is the command name)
    moderatorOnlyCommands: ['botattack', 'antivpn']
  
  # Slash commands permissions
  interactionCommands:
    # Enable slash commands permissions
    enable: true

    # Register slash commands
    registerSlashCommands: true

    # Restrict commands for admin only (This is the command name)
    adminOnlyCommands: ['stop']

    # Command for moderator with kick and ban perms (This is the command name)
    moderatorOnlyCommands: []

# Ignored channels based on IDs
blacklistChannels:            
  enabled: false  # Enable blacklisted channels

  # List of blacklisted channels
  channels: []
  convertToWhitelist: false  # Convert channels to whitelisted channels

# Custom bot presence
presence:
  enabled: true  # Enable presence
  status: ['dnd']  # Status of bot (online, idle, dnd, offline)  [this can be a string or an object for random value]
  type: ['watching']  # Type of status (playing, listening, watching, streaming) or enter a custom status  [this can be a string or an object for random value]
  activityName: ['VPN users & McDown', 'VPN users', 'McDown', '#🤖・chat-for-boring-ppl', 'you']  # Name your activity [this can be a string or an object for random value]

inviteFormat: https://discord.com/oauth2/authorize?client_id=%id%&permissions=8&scope=bot%20applications.commands   # Invite format for bot
language: 'config/language.yml'   # Langage file 
modulesFolder: 'modules'  # Define where's your modules

version: 1.4.1    # Version (don't modify this value)