# token: ODQxOTU2MTU1MTkwNDExMjg0.YJuSxg._ziWK80P0SVQv0MMAAmP5Kub9T8 # Bot token
token: ODU0MjMwMzY2MDg4MjAwMjMz.YMg6Bg.xvfAbyBdzPpnxVFFeTepruSuqfw

embedColor: '#19AFFF'  # Colors for embed messages
commandPrefix: '!'  # Prefix for commands
owner: 'Ghexter'  # Who owns this bot

guildId: # Only register slash commands for the given guild.

# Command permissions
permissions:
  # Restrict commands for admin only (This is the script name)
  adminOnlyCommands:
    - 'stop'

  # Command for moderator with kick and ban perms (This is the script name)
  moderatorOnlyCommands: 
    - 'version'
    - 'botattack'
    - 'antivpn'

# Slash commands
slashCommands:
  enabled: true

# Ignored channels based on IDs
blacklistChannels:            
  enabled: false  # Enable blacklisted channels

  # List of blacklisted channels
  channels: []
  convertToWhitelist: false  # Convert channels to whitelisted channels

# Custom bot presence
presence:
  enabled: true  # Enable presence
  status: ['dnd']  # Status of bot (online, idle, dnd, offline)  [this can be a string or an object for random value]
  type: ['watching']  # Type of status (playing, listening, watching, streaming) or enter a custom status  [this can be a string or an object for random value]
  activityName: ['VPN users & McDown', 'Vpn users', 'McDown', '#🤖・chat-for-boring-ppl', 'you']  # Name your activity [this can be a string or an object for random value]

inviteFormat: https://discord.com/oauth2/authorize?client_id=%id%&permissions=8&scope=bot%20applications.commands   # Invite format for bot
language: 'config/language.yml'
modulesFolder: 'modules'

version: 1.1.2    # Version (don't modify this value)