channelsWhiteList:
  enabled: true
  channelIds:
    - '882528979653918770'
  convertToBlacklist: false
messageSend:
  sendAsEmbed: true
queries:
  - language: en
    id: ask.version
    trigger: what's the server version?
    answer: |-
      The server currently supports:
      ```
      Minecraft 1.18.1 to Minecraft 1.9.4
      ``` 
      *it's not recommended to use `1.15` and below.*
  - language: en
    id: ask.ip
    trigger: what's the IP address?
    answer: |-
      **Our Word Server IP**
      ```yml
      play.ourmcworld.ml
      ```
      ```yml
      OurMcWorldArchive.aternos.me
      ```
      *These IPs are same server.*
  - language: en
    id: ask.bedrockEdition
    trigger: Is this server available for bedrock?
    answer: This server is only available for Java Edition and there's no plan to support Bedrock Edition at the moment.
  - language: en
    id: ask.bedrockEdition
    trigger: Is this server supports for bedrock?
  - language: en
    id: ask.bedrockEdition
    trigger: Bedrock Edition support?
  - language: en
    id: ask.bedrockEdition
    trigger: Does this server have geyser?
  
  - language: en
    id: miscellaneous.ded
    trigger: ded server
    answer: rips
  - language: en
    id: miscellaneous.sus
    trigger: sus suspicious
    answer: sus
  - language: en
    id: miscellaneous.hidden
    trigger: HiddenPlayer
    answer: fr