autoEmbedIp:
  enabled: true
  ignoreBots: false
  fetchErrorLimit: 3
  requireServerIP: true
  deleteAfterInactive: true
  disableMultipleUpload: true
  allowedChannelIds:
  - '911491519389786142'

#  - '876048902187540520'
messages:
  pending: Loading...
  noIpProvided: |-
    Please enter your server IP address
    > Make sure your server ip does not conflict with other IP addresses or is above any other non minecraft server IP address.
  connectionError: Can't connect to server
  alreadyUploaded: You have already provided your server address
  serverEmbedDescription: |-
    This server is **online**.
    **%players_online%/%players_max%** players playing on **%server_version%**
  embedColors:
    online: "#43b582"
    error: "#ff3838"
    buffer: "#939393"
