autoEmbedIp:
  enabled: true
  ignoreBots: true
  fetchErrorLimit: 5
  requireServerIP: true
  deleteAfterInactive: true
  disableMultipleUpload: true
  allowedChannelIds: ['876048637677961227', '876048902187540520']
messages:
  pending: Loading...
  noIpProvided: |-
    Please enter your server IP address
    > If your server is not an aternos server. add the following to embed your server
    > ```yml
    > IP: yourserver.ip
    > ```
  connectionError: Can't connect to server
  alreadyUploaded: You have already provided your server address
  serverEmbedDescription: |-
    This server is **online**.
    **%players_online%/%players_max%** players playing on **%server_version%**
  embedColors:
    online: "#43b582"
    error: "#ff3838"
    buffer: "#939393"
