playerRoles:
  colors:
    Admin+: green
    Admin: yellow
    Moderator: blue
channels:
  - messagesChannelId: "883269578791206942"
    consoleChannelId: "884753588105117726"
    playerChats:
      receive: true
      send: true
    discordChats:
      receive: true
      send: true
    botId: "841956155190411284"
  - messagesChannelId: "925654450713026560"
    consoleChannelId: "925654581411729439"
    playerChats:
      receive: true
      send: true
    discordChats:
      receive: true
      send: true
    botId: "841956155190411284"
  - messagesChannelId: "946044380920295444"
    consoleChannelId: "946044628661075999"
    playerChats:
      receive: true
      send: true
    discordChats:
      receive: true
      send: true
    botId: "841956155190411284"
