playerRoles:
  colors:
    Admin+: green
    Admin: yellow
    Moderator: blue
channels:
  - messagesChannelId: "883269578791206942"
    consoleChannelId: "884753588105117726"
    playerChats:
      receive: true
      send: true
    discordChats:
      receive: true
      send: true
    botId: "841956155190411284"
  - messagesChannelId: "925654450713026560"
    consoleChannelId: "925654581411729439"
    playerChats:
      receive: true
      send: true
    discordChats:
      receive: true
      send: true
    botId: "841956155190411284"
  - messagesChannelId: "856557072166420511"
    consoleChannelId: "841984692026474526"
    playerChats:
      receive: true
      send: true
    discordChats:
      receive: false
      send: true
    botId: "841956155190411284"